language: node_js
install:
  - "npm install"
  - "npm run bootstrap"
  - "npm run prettier"
  - "npm run tslint"
  - "npm run tsc"
  - "npm run test"



node_js:
  - "12"
  - "10"

notifications:
  email:
    recipients:
      - team@jovo.tech
    on_success: never
    on_failure: always

